addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
  })

  async function handleRequest(request) {
  const url = new URL(request.url);
  const message = url.searchParams.get('message');
  const logo = url.searchParams.get('logo');

  if (!message) {
      return new Response(JSON.stringify({ error: 'Missing message parameter' }), { status: 400, headers: { 'Content-Type': 'application/json' }});
  }

                const bodytemp = [
                    "square",
                        "mosaic",
                            "dot",
                                "circle",
                                    "circle-zebra",
                                        "circle-zebra-vertical",
                                            "circular",
                                                "edge-cut",
                                                    "edge-cut-smooth",
                                                        "japnese",
                                                            "leaf",
                                                                "pointed",
                                                                    "pointed-edge-cut",
                                                                        "pointed-in",
                                                                            "pointed-in-smooth",
                                                                                "pointed-smooth",
                                                                                    "round",
                                                                                        "rounded-in",
                                                                                            "rounded-in-smooth",
                                                                                                "rounded-pointed",
                                                                                                    "star",
                                                                                                        "diamond"
                                                                                                          ];
                                                                                                            const eyetemp = [
                                                                                                                "frame0",
                                                                                                                    "frame1",
                                                                                                                        "frame2",
                                                                                                                            "frame3",
                                                                                                                                "frame4",
                                                                                                                                    "frame5",
                                                                                                                                        "frame6",
                                                                                                                                            "frame7",
                                                                                                                                                "frame8",
                                                                                                                                                    "frame9",
                                                                                                                                                        "frame10",
                                                                                                                                                            "frame11",
                                                                                                                                                                "frame12",
                                                                                                                                                                    "frame13",
                                                                                                                                                                        "frame14",
                                                                                                                                                                            "frame15",
                                                                                                                                                                                "frame16"
                                                                                                                                                                                  ];
                                                                                                                                                                                    const eyeballtemp = [
                                                                                                                                                                                        "ball0",
                                                                                                                                                                                            "ball1",
                                                                                                                                                                                                "ball2",
                                                                                                                                                                                                    "ball3",
                                                                                                                                                                                                        "ball4",
                                                                                                                                                                                                            "ball5",
                                                                                                                                                                                                                "ball6",
                                                                                                                                                                                                                    "ball7",
                                                                                                                                                                                                                        "ball8",
                                                                                                                                                                                                                            "ball9",
                                                                                                                                                                                                                                "ball10",
                                                                                                                                                                                                                                    "ball11",
                                                                                                                                                                                                                                        "ball12",
                                                                                                                                                                                                                                            "ball13",
                                                                                                                                                                                                                                                "ball14",
                                                                                                                                                                                                                                                    "ball15",
                                                                                                                                                                                                                                                        "ball16",
                                                                                                                                                                                                                                                            "ball17",
                                                                                                                                                                                                                                                                "ball18",
                                                                                                                                                                                                                                                                    "ball19"
                                                                                                                                                                                                                                                                      ];
                                                                                                                                                                                                                                                                        const randomEye = eyetemp[Math.floor(Math.random() * eyetemp.length)];
                                                                                                                                                                                                                                                                          const randomball = eyeballtemp[Math.floor(Math.random() * eyeballtemp.length)];
                                                                                                                                                                                                                                                                            const randombody = bodytemp[Math.floor(Math.random() * bodytemp.length)];

                                                                                                                                                                                                                                                                              function getRandomGradientColors() {
                                                                                                                                                                                                                                                                                  // Generate random RGB values for the first color
                                                                                                                                                                                                                                                                                      const r1 = Math.floor(Math.random() * 256);
                                                                                                                                                                                                                                                                                          const g1 = Math.floor(Math.random() * 256);
                                                                                                                                                                                                                                                                                              const b1 = Math.floor(Math.random() * 256);

                                                                                                                                                                                                                                                                                                  // Convert RGB to hexadecimal format for the first color
                                                                                                                                                                                                                                                                                                      const color1 =
                                                                                                                                                                                                                                                                                                            "#" + ((1 << 24) + (r1 << 16) + (g1 << 8) + b1).toString(16).slice(1);

                                                                                                                                                                                                                                                                                                                // Generate random RGB values for the second color
                                                                                                                                                                                                                                                                                                                    const r2 = Math.floor(Math.random() * 256);
                                                                                                                                                                                                                                                                                                                        const g2 = Math.floor(Math.random() * 256);
                                                                                                                                                                                                                                                                                                                            const b2 = Math.floor(Math.random() * 256);

                                                                                                                                                                                                                                                                                                                                // Convert RGB to hexadecimal format for the second color
                                                                                                                                                                                                                                                                                                                                    const color2 =
                                                                                                                                                                                                                                                                                                                                          "#" + ((1 << 24) + (r2 << 16) + (g2 << 8) + b2).toString(16).slice(1);

                                                                                                                                                                                                                                                                                                                                              return [color1, color2];
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                  // Get random gradient colors
                                                                                                                                                                                                                                                                                                                                                    const randomGradientColors = getRandomGradientColors();

                                                                                                                                                                                                                                                                                                                                                      const qrData = await fetch("https://api.qrcode-monkey.com/qr/custom", {
                                                                                                                                                                                                                                                                                                                                                          method: "POST",
                                                                                                                                                                                                                                                                                                                                                              headers: {
                                                                                                                                                                                                                                                                                                                                                                    "Content-Type": "application/json;charset=utf-8"
                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                            body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                  data: message,
                                                                                                                                                                                                                                                                                                                                                                                        config: {
                                                                                                                                                                                                                                                                                                                                                                                                body: randombody,
                                                                                                                                                                                                                                                                                                                                                                                                        eye: randomEye,
                                                                                                                                                                                                                                                                                                                                                                                                                eyeBall: randomball,
                                                                                                                                                                                                                                                                                                                                                                                                                        erf1: [],
                                                                                                                                                                                                                                                                                                                                                                                                                                erf2: [],
                                                                                                                                                                                                                                                                                                                                                                                                                                        erf3: [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                brf1: [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                        brf2: [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                brf3: [],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        bodyColor: "#000000",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bgColor: "#FFFFFF",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        eye1Color: "#000000",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                eye2Color: "#000000",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        eye3Color: "#000000",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                eyeBall1Color: "#000000",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        eyeBall2Color: "#000000",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                eyeBall3Color: "#000000",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        gradientColor1: randomGradientColors[0],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gradientColor2: randomGradientColors[1],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        gradientType: "linear",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gradientOnEyes: "true",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        logo: logo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logoMode: "default"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            size: 2000,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  download: "imageUrl",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        file: "jpg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!qrData.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return new Response(JSON.stringify({ error: 'Failed to generate QR code' }), { status: 500, headers: { 'Content-Type': 'application/json' } });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const qrImageData = await qrData.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          let qrImageUrl = qrImageData.imageUrl;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Add 'https://' to the URL if it doesn't already start with 'https://'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!qrImageUrl.startsWith('https:')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  qrImageUrl = 'https:' + qrImageUrl;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Return the QR code image URL in JSON format
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return new Response(JSON.stringify({ qrImageUrl }), { headers: { 'Content-Type': 'application/json' } });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
